default:
  &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  
development:
  <<: *default
  database: shiftmanager_development

production:
  <<: *default
  database: shiftmanager_production

test:
  <<: *default
  database: shiftmanager_test

